# Generated by Django 4.1.8 on 2023-05-05 20:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'blockquote']))])), ('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(max_length=50)), ('code', wagtail.blocks.TextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
