# Generated by Django 4.1.8 on 2023-05-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blogpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
