# Generated by Django 4.1.9 on 2023-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="intro_heading",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
