# Generated by Django 4.1.9 on 2023-05-04 05:00

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_intro_heading_homepage_intro_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
